# Generated by Django 6.0.4 on 2026-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('workspaces', '0002_workspace_description_workspace_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to='employees.employee'),
        ),
    ]
