# Generated by Django 6.0.4 on 2026-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('api_address', models.TextField(blank=True, default='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('geocode_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
