# Generated by Django 6.0.4 on 2026-05-04 00:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('stopped', 'Stopped')], default='running', max_length=10)),
                ('total', models.IntegerField(default=0)),
                ('done', models.IntegerField(default=0)),
                ('ok', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('stop_requested', models.BooleanField(default=False)),
                ('log', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
