# Generated by Django 6.0.4 on 2026-05-04 00:26

from django.db import migrations, models


def backfill_address_score(apps, _schema_editor):
    from employees.utils import address_match_score
    Employee = apps.get_model('employees', 'Employee')
    bulk = []
    for emp in Employee.objects.all():
        emp.address_score = address_match_score(emp.address, emp.api_address)
        bulk.append(emp)
    Employee.objects.bulk_update(bulk, ['address_score'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_address_score, migrations.RunPython.noop),
    ]
