# Generated by Django 6.0.4 on 2026-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='duration_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
