# Generated by Django 6.0.4 on 2026-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_routegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='color',
            field=models.CharField(default='#3498DB', max_length=7),
        ),
        migrations.AlterField(
            model_name='route',
            name='direction',
            field=models.CharField(choices=[('inbound', 'İş Yerine Geliş'), ('outbound', 'İş Yerinden Çıkış')], max_length=10),
        ),
    ]
