# Generated by Django 6.0.4 on 2026-04-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_route_color_alter_route_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='isochrone',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
